// Mock data for dashboard

import { DashboardState } from "@/types";

export const mockDashboardData: DashboardState = {
  operacao: {
    status: "normal",
    mensagem: "Operação estável",
    ultimaAtualizacao: new Date(Date.now() - 2 * 60000), // 2 minutes ago
    ocorrenciasCriticas: 18,
    ocorrenciasParaPriorizar: 5,
  },

  kpis: [
    {
      id: "paradas",
      label: "PARADAS",
      value: 1234,
      variation: 8.2,
      trend: "up",
      status: "normal",
      description: "vs período anterior",
    },
    {
      id: "minutos-parada",
      label: "MINUTOS DE PARADA",
      value: "125k",
      unit: "min",
      status: "normal",
      description: "tempo total",
    },
    {
      id: "criticos",
      label: "CRÍTICOS",
      value: 18,
      status: "critical",
      description: "3 novas ocorrências",
      isCritical: true,
    },
    {
      id: "crit-cronicios",
      label: "CRIT-CRÔN",
      value: 5,
      status: "warning",
      description: "prioridade imediata",
    },
  ],

  pareto: [
    {
      id: "emp-var",
      label: "EMP-VAR",
      causa: "Empenamento de Válvula",
      minutos: 420,
      percentual: 28.4,
      percentualAcumulado: 28.4,
      frequencia: 12,
    },
    {
      id: "emp-198",
      label: "EMP-198",
      causa: "Empenamento 198",
      minutos: 285,
      percentual: 19.2,
      percentualAcumulado: 47.6,
      frequencia: 8,
    },
    {
      id: "enc-stc",
      label: "ENC-STC",
      causa: "Encravamento da Corrente",
      minutos: 198,
      percentual: 13.4,
      percentualAcumulado: 61.0,
      frequencia: 6,
    },
    {
      id: "dos-n2",
      label: "DOS-N2",
      causa: "Dosagem N2 Incorreta",
      minutos: 156,
      percentual: 10.5,
      percentualAcumulado: 71.5,
      frequencia: 4,
    },
    {
      id: "cal-temp",
      label: "CAL-TEMP",
      causa: "Calibração Temperatura",
      minutos: 98,
      percentual: 6.6,
      percentualAcumulado: 78.1,
      frequencia: 3,
    },
    {
      id: "led-oleo",
      label: "LED-ÓLEO",
      causa: "Leitura Óleo Incorreta",
      minutos: 68,
      percentual: 4.6,
      percentualAcumulado: 82.7,
      frequencia: 2,
    },
    {
      id: "otros",
      label: "OTROS",
      causa: "Outras causas",
      minutos: 255,
      percentual: 17.3,
      percentualAcumulado: 100.0,
      frequencia: 15,
    },
  ],

  jackKnife: [
    {
      id: "emp-var",
      causa: "EMP-VAR",
      frequencia: 12,
      impacto: 420,
      minutos: 420,
      quadrante: "altoimp-altafreq",
    },
    {
      id: "emp-198",
      causa: "EMP-198",
      frequencia: 8,
      impacto: 285,
      minutos: 285,
      quadrante: "altoimp-altafreq",
    },
    {
      id: "enc-stc",
      causa: "ENC-STC",
      frequencia: 6,
      impacto: 198,
      minutos: 198,
      quadrante: "altoimp-altafreq",
    },
    {
      id: "dos-n2",
      causa: "DOS-N2",
      frequencia: 4,
      impacto: 156,
      minutos: 156,
      quadrante: "altoimp-baixafreq",
    },
    {
      id: "cal-temp",
      causa: "CAL-TEMP",
      frequencia: 3,
      impacto: 98,
      minutos: 98,
      quadrante: "altoimp-baixafreq",
    },
    {
      id: "led-oleo",
      causa: "LED-ÓLEO",
      frequencia: 2,
      impacto: 68,
      minutos: 68,
      quadrante: "baixoimp-baixafreq",
    },
  ],

  problemasEmAcao: [
    {
      id: "p1",
      posicao: 1,
      codigo: "EMP-VAR",
      descricao: "Empenamento de Válvula",
      minutos: 420,
      impacto: "critico",
      frequencia: 12,
      status: "novo",
    },
    {
      id: "p2",
      posicao: 2,
      codigo: "EMP-198",
      descricao: "Empenamento 198",
      minutos: 285,
      impacto: "critico",
      frequencia: 8,
      status: "em-acompanhamento",
    },
    {
      id: "p3",
      posicao: 3,
      codigo: "ENC-STC",
      descricao: "Encravamento da Corrente",
      minutos: 198,
      impacto: "alto",
      frequencia: 6,
      status: "novo",
    },
    {
      id: "p4",
      posicao: 4,
      codigo: "DOS-N2",
      descricao: "Dosagem N2 Incorreta",
      minutos: 156,
      impacto: "alto",
      frequencia: 4,
      status: "novo",
    },
    {
      id: "p5",
      posicao: 5,
      codigo: "CAL-TEMP",
      descricao: "Calibração Temperatura",
      minutos: 98,
      impacto: "medio",
      frequencia: 3,
      status: "em-acompanhamento",
    },
  ],

  filtro: {
    planta: "São Paulo",
    linha: "Linha 04",
    produto: "Todos",
    dataInicial: new Date("2026-09-01"),
    dataFinal: new Date("2026-09-16"),
    indicador: "Tempo de parada",
    topCausas: 10,
  },

  isLoading: false,
};
